# Generated by Django 6.0.4 on 2026-04-20 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticia',
            options={'ordering': ['-fecha'], 'verbose_name': 'Noticia', 'verbose_name_plural': 'Noticias'},
        ),
        migrations.AlterModelOptions(
            name='postulacion',
            options={'ordering': ['-fecha'], 'verbose_name': 'Postulación', 'verbose_name_plural': 'Postulaciones'},
        ),
        migrations.RenameField(
            model_name='noticia',
            old_name='contenido',
            new_name='descripcion',
        ),
        migrations.AddField(
            model_name='noticia',
            name='etiqueta',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='noticia',
            name='media_urls',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='noticia',
            name='youtube_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='postulacion',
            name='direccion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='postulacion',
            name='distrito',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='postulacion',
            name='dni',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='postulacion',
            name='estatura',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postulacion',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postulacion',
            name='genero',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='postulacion',
            name='grado_instruccion',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='postulacion',
            name='peso',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='imagen_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
