# Generated by Django 6.0.4 on 2026-04-20 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_noticia_options_alter_postulacion_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vitrina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=100)),
                ('nombre', models.CharField(blank=True, max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_ingreso', models.CharField(blank=True, max_length=30)),
                ('foto_url', models.URLField(blank=True, max_length=500)),
                ('orden', models.IntegerField(default=9999)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vitrina',
                'verbose_name_plural': 'Vitrina',
                'ordering': ['orden'],
            },
        ),
        migrations.AddField(
            model_name='postulacion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20),
        ),
        migrations.CreateModel(
            name='Efectivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(blank=True, max_length=20)),
                ('grado', models.CharField(blank=True, choices=[('Brigadier', 'Brigadier'), ('Ten. Brigadier', 'Ten. Brigadier'), ('Capitán', 'Capitán'), ('Teniente', 'Teniente'), ('Sub Teniente', 'Sub Teniente'), ('Seccionario', 'Seccionario'), ('Aspirante', 'Aspirante'), ('Postulante', 'Postulante')], max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('foto_url', models.URLField(blank=True, max_length=500)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='efectivo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Efectivo',
                'verbose_name_plural': 'Efectivos',
            },
        ),
    ]
