# Generated by Django 6.0.4 on 2026-04-21 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_vitrina_postulacion_estado_efectivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='tipo',
            field=models.CharField(default='Curso', max_length=20),
        ),
        migrations.AlterField(
            model_name='efectivo',
            name='grado',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
